/**
 * @module orchestration/coding/__tests__/safe-commit
 *
 * Tests for the coding-mode commit safety helpers (Task #209).
 *
 * Cover the four "done looks like" cases from the task spec:
 *   (a) fresh repo with no `.gitignore` + an oversize binary → push refused
 *   (b) repo with partial `.gitignore` → only missing entries appended
 *   (c) `.env` always excluded even when `.gitignore` doesn't list it
 *   (d) clean repo with no offending files → behaviour unchanged
 *
 * The helpers are pure I/O against `repoDir`, so each test sets up a
 * tiny throwaway directory under the OS temp dir and tears it down on
 * exit. We deliberately do NOT shell out to `git`: the helpers are
 * `git`-free by design, and that's what makes them testable here
 * without forking processes.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  mkdirSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  DEFAULT_GITIGNORE_ENTRIES,
  MAX_COMMITTABLE_BYTES,
  ensureSafeGitignore,
  findUnsafeFiles,
  prepareSafeCommit,
  installSafeCommitHooks,
  CommitSafetyError,
  formatCommitSafetyMessage,
} from '../safe-commit.js';

let repoDir: string;

beforeEach(() => {
  repoDir = mkdtempSync(join(tmpdir(), 'safe-commit-test-'));
});

afterEach(() => {
  try { rmSync(repoDir, { recursive: true, force: true }); } catch { /* best effort */ }
});

describe('ensureSafeGitignore', () => {
  it('creates a fresh .gitignore with the full default set when none exists', () => {
    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(true);
    expect(result.added).toEqual([...DEFAULT_GITIGNORE_ENTRIES]);
    const content = readFileSync(result.gitignorePath, 'utf-8');
    expect(content).toMatch(/Auto-generated by OrionOmega coding mode/);
    for (const entry of DEFAULT_GITIGNORE_ENTRIES) {
      expect(content).toContain(entry);
    }
  });

  it('appends only the missing entries to a partial .gitignore (case b)', () => {
    // Pretend the user already curated a few entries by hand.
    const userCurated = '# my own ignores\nnode_modules/\ndist/\n*.log\n';
    writeFileSync(join(repoDir, '.gitignore'), userCurated, 'utf-8');

    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(false);

    // The three entries above are part of the default set, so they must
    // NOT appear in `added` — that's the user-curated content we promised
    // to preserve.
    expect(result.added).not.toContain('node_modules/');
    expect(result.added).not.toContain('dist/');
    expect(result.added).not.toContain('*.log');
    // Entries the user didn't list must show up.
    expect(result.added).toContain('.env');
    expect(result.added).toContain('.next/');
    expect(result.added).toContain('coverage/');

    const after = readFileSync(result.gitignorePath, 'utf-8');
    // Original content must be preserved verbatim at the top.
    expect(after.startsWith(userCurated)).toBe(true);
    // Appended block carries the audit-trail comment.
    expect(after).toMatch(/safe-commit defaults/);
  });

  it('is a no-op when the .gitignore already covers every default entry (case d)', () => {
    const full = DEFAULT_GITIGNORE_ENTRIES.join('\n') + '\n';
    writeFileSync(join(repoDir, '.gitignore'), full, 'utf-8');
    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(false);
    expect(result.added).toEqual([]);
    // File contents are byte-for-byte unchanged: no spurious append, no
    // trailing-newline rewriting that would noisy-up the user's diff.
    expect(readFileSync(result.gitignorePath, 'utf-8')).toBe(full);
  });

  it('treats whitespace-padded entries as already-present (no duplicate appends)', () => {
    writeFileSync(join(repoDir, '.gitignore'), '  node_modules/  \n', 'utf-8');
    const result = ensureSafeGitignore(repoDir);
    expect(result.added).not.toContain('node_modules/');
  });
});

describe('findUnsafeFiles', () => {
  it('flags files larger than the 95 MB GitHub-safe ceiling (case a)', () => {
    // We use a small `maxBytes` instead of writing 95 MB to disk —
    // behaviour is identical, runtime is a millisecond.
    writeFileSync(join(repoDir, 'big.bin'), 'x'.repeat(2048), 'utf-8');
    writeFileSync(join(repoDir, 'small.txt'), 'hello', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir, { maxBytes: 1024 });
    const oversize = unsafe.filter((u) => u.reason === 'oversize');
    expect(oversize).toHaveLength(1);
    expect(oversize[0]?.path).toBe('big.bin');
    expect(oversize[0]?.bytes).toBe(2048);
  });

  it('flags .env, .env.local, and *.env.production as secrets (case c)', () => {
    writeFileSync(join(repoDir, '.env'), 'SECRET=1', 'utf-8');
    writeFileSync(join(repoDir, '.env.local'), 'SECRET=2', 'utf-8');
    writeFileSync(join(repoDir, '.env.production'), 'SECRET=3', 'utf-8');
    // .env.example must NOT be flagged — it's the conventional template.
    writeFileSync(join(repoDir, '.env.example'), 'SECRET=', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    const paths = unsafe.filter((u) => u.reason === 'secret').map((u) => u.path).sort();
    expect(paths).toEqual(['.env', '.env.local', '.env.production']);
  });

  it('flags *.pem / *.key / *.p12 as secrets', () => {
    writeFileSync(join(repoDir, 'cert.pem'), 'pem', 'utf-8');
    writeFileSync(join(repoDir, 'private.key'), 'key', 'utf-8');
    writeFileSync(join(repoDir, 'truststore.p12'), 'p12', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe.map((u) => u.path).sort()).toEqual(['cert.pem', 'private.key', 'truststore.p12']);
    expect(unsafe.every((u) => u.reason === 'secret')).toBe(true);
  });

  it('flags top-level node_modules / dist / .next as build artefacts', () => {
    mkdirSync(join(repoDir, 'node_modules', '@scope', 'pkg'), { recursive: true });
    writeFileSync(join(repoDir, 'node_modules', '@scope', 'pkg', 'index.js'), 'x', 'utf-8');
    mkdirSync(join(repoDir, 'dist'), { recursive: true });
    writeFileSync(join(repoDir, 'dist', 'bundle.js'), 'x', 'utf-8');
    mkdirSync(join(repoDir, '.next'), { recursive: true });
    writeFileSync(join(repoDir, '.next', 'app.js'), 'x', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    const buildPaths = unsafe.filter((u) => u.reason === 'build-artefact').map((u) => u.path).sort();
    expect(buildPaths).toEqual([
      '.next/app.js',
      'dist/bundle.js',
      'node_modules/@scope/pkg/index.js',
    ]);
  });

  it('does NOT flag legitimately-named files that merely contain artefact substrings', () => {
    // `node_modules.md` under `docs/` is a perfectly valid documentation
    // file. The deny-list is anchored to the *first* path segment so this
    // doesn't get caught.
    mkdirSync(join(repoDir, 'docs'), { recursive: true });
    writeFileSync(join(repoDir, 'docs', 'node_modules.md'), '# notes', 'utf-8');
    writeFileSync(join(repoDir, 'README.md'), '# readme', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe).toEqual([]);
  });

  it('skips the .git directory entirely (never reports git internals)', () => {
    mkdirSync(join(repoDir, '.git', 'objects'), { recursive: true });
    // A pretend pack file over 95 MB — this would be a false positive if
    // we walked .git, since git's own object DB legitimately exceeds the
    // commit limit on large repos.
    writeFileSync(join(repoDir, '.git', 'objects', 'pack-xxx'), 'x'.repeat(2048), 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir, { maxBytes: 1024 });
    expect(unsafe).toEqual([]);
  });

  it('returns no unsafe files for a clean source-only repo (case d)', () => {
    writeFileSync(join(repoDir, 'README.md'), '# project', 'utf-8');
    writeFileSync(join(repoDir, 'package.json'), '{}', 'utf-8');
    mkdirSync(join(repoDir, 'src'), { recursive: true });
    writeFileSync(join(repoDir, 'src', 'index.ts'), 'export {};', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe).toEqual([]);
  });
});

describe('prepareSafeCommit', () => {
  it('reproduces the user\'s Legal-repo failure: ensures gitignore + throws on oversize node_modules (case a)', () => {
    // Fresh repo, no .gitignore — exactly the state the Legal repo was in.
    mkdirSync(join(repoDir, 'node_modules', '@next', 'swc-linux-x64-gnu'), { recursive: true });
    // Use a small `maxBytes` to simulate the 125 MB next-swc binary
    // without writing 125 MB of disk in the test.
    const huge = join(repoDir, 'node_modules', '@next', 'swc-linux-x64-gnu', 'next-swc.linux-x64-gnu.node');
    writeFileSync(huge, 'x'.repeat(2048), 'utf-8');
    writeFileSync(join(repoDir, 'package.json'), '{}', 'utf-8');

    // The bare prepareSafeCommit (default 95 MB) wouldn't trip on a 2 KB
    // file, but our findUnsafeFiles also flags it as a build artefact, so
    // the throw still fires for the right reason.
    expect(() => prepareSafeCommit(repoDir)).toThrowError(CommitSafetyError);
    // And the .gitignore was created on the way out (so the next run
    // wouldn't even produce the same files in the staging set).
    expect(existsSync(join(repoDir, '.gitignore'))).toBe(true);
  });

  it('returns a clean result with the gitignore audit trail when nothing is unsafe (case d)', () => {
    writeFileSync(join(repoDir, 'README.md'), '# project', 'utf-8');
    const result = prepareSafeCommit(repoDir);
    expect(result.refused).toEqual([]);
    expect(result.gitignore.created).toBe(true);
    expect(result.gitignore.added.length).toBeGreaterThan(0);
  });
});

describe('formatCommitSafetyMessage', () => {
  it('lists each offending file with a human-readable size and reason', () => {
    const msg = formatCommitSafetyMessage([
      { path: 'node_modules/big.bin', reason: 'oversize', bytes: 125 * 1024 * 1024 },
      { path: '.env', reason: 'secret', bytes: 42 },
    ]);
    expect(msg).toMatch(/Refusing to commit 2 files/);
    expect(msg).toContain('node_modules/big.bin');
    expect(msg).toContain('125.00 MB');
    expect(msg).toContain('.env');
    expect(msg).toContain('secret');
    expect(msg).toMatch(/Git LFS/);
  });
});

describe('installSafeCommitHooks', () => {
  it('writes BOTH executable pre-commit and pre-push hooks into .git/hooks/', () => {
    mkdirSync(join(repoDir, '.git'), { recursive: true });
    const result = installSafeCommitHooks(repoDir);
    expect(result.installed).toBe(true);
    expect(result.preCommitHookPath).toBe(join(repoDir, '.git', 'hooks', 'pre-commit'));
    expect(result.prePushHookPath).toBe(join(repoDir, '.git', 'hooks', 'pre-push'));
    expect(existsSync(result.preCommitHookPath)).toBe(true);
    expect(existsSync(result.prePushHookPath)).toBe(true);
    const fs = require('node:fs');
    // Both hooks must be executable — git silently skips non-exec ones.
    expect(fs.statSync(result.preCommitHookPath).mode & 0o100).toBeTruthy();
    expect(fs.statSync(result.prePushHookPath).mode & 0o100).toBeTruthy();
  });

  it('embeds the 95 MB ceiling, build-artefact deny-list, and secret patterns in the pre-push hook', () => {
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    const { prePushHookPath } = installSafeCommitHooks(repoDir);
    const body = readFileSync(prePushHookPath, 'utf-8');
    expect(body).toMatch(/^#!\/usr\/bin\/env perl/);
    expect(body).toContain('95 * 1024 * 1024');
    // True NUL-record processing via `local $/ = "\0"` for the inner
    // ls-tree walk. No shell-level round-trip means filenames with
    // embedded newlines/tabs survive intact through the classifier.
    expect(body).toContain('local $/ = "\\0"');
    // Pre-push walks every commit being pushed, NOT just HEAD.
    expect(body).toContain("'git', 'rev-list'");
    expect(body).toContain("'git', 'ls-tree', '-r', '-l', '-z'");
    // Stdin is the source of pushed-ref ranges.
    expect(body).toMatch(/while \(my \$line = <STDIN>\)/);
    // HEAD-tree fallback for manual invocation / no-stdin tests.
    expect(body).toMatch(/fallback_to_head/);
    // Control-char rejection range MUST cover TAB (0x09), LF (0x0A),
    // and CR (0x0D). The 0x01-0x1F range does so by construction.
    expect(body).toMatch(/\[\\x01-\\x1f\]/);
    // Build artefacts — anchored first-segment match in the perl regex.
    expect(body).toMatch(/node_modules\|/);
    expect(body).toMatch(/\.next\|/);
    expect(body).toMatch(/dist\|build/);
    expect(body).toMatch(/coverage/);
    // Secrets / key material — basename suffix match.
    expect(body).toMatch(/pem\|key\|p12\|pfx/);
    // Conventional placeholders must be allowed through.
    expect(body).toContain('.env.example');
    expect(body).toContain('.env.sample');
    expect(body).toMatch(/refusing to push/);
    expect(body).toMatch(/exit 1/);
    expect(body).toMatch(/control characters/);
    // History-purge guidance for pre-existing bad blobs.
    expect(body).toMatch(/git filter-repo/);
  });

  it('embeds the same deny-list in the pre-commit hook, anchored on the staged index', () => {
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    const { preCommitHookPath } = installSafeCommitHooks(repoDir);
    const body = readFileSync(preCommitHookPath, 'utf-8');
    expect(body).toMatch(/^#!\/usr\/bin\/env perl/);
    expect(body).toContain('95 * 1024 * 1024');
    // Pre-commit reads the staged INDEX (not HEAD / not the working tree).
    expect(body).toContain("'git', 'ls-files', '-s', '-z'");
    // Batch-resolves blob sizes via cat-file in one IPC::Open2 pass
    // so large indices don't fork-bomb.
    expect(body).toContain('IPC::Open2');
    expect(body).toContain('cat-file');
    expect(body).toMatch(/\[\\x01-\\x1f\]/);
    expect(body).toMatch(/node_modules\|/);
    expect(body).toMatch(/pem\|key\|p12\|pfx/);
    expect(body).toContain('.env.example');
    expect(body).toMatch(/refusing this commit/);
    expect(body).toMatch(/exit 1/);
  });

  it('overwrites stale hooks on every install (idempotent re-installation)', () => {
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    const stalePush = join(repoDir, '.git', 'hooks', 'pre-push');
    const staleCommit = join(repoDir, '.git', 'hooks', 'pre-commit');
    writeFileSync(stalePush, '#!/bin/sh\necho stale push\n', 'utf-8');
    writeFileSync(staleCommit, '#!/bin/sh\necho stale commit\n', 'utf-8');
    const { installed } = installSafeCommitHooks(repoDir);
    expect(installed).toBe(true);
    expect(readFileSync(stalePush, 'utf-8')).toMatch(/OrionOmega safe-commit hook/);
    expect(readFileSync(staleCommit, 'utf-8')).toMatch(/OrionOmega safe-commit hook/);
  });

  it('is a no-op (installed=false) when .git is missing — no fabricated git dir', () => {
    const result = installSafeCommitHooks(repoDir);
    expect(result.installed).toBe(false);
    expect(existsSync(join(repoDir, '.git'))).toBe(false);
  });

  // Round-5 review: failure-injection. The atomic install MUST leave
  // no partial state behind. If the pre-push side of the install
  // can't land (e.g. someone wedged a non-writable file at
  // .git/hooks/pre-push), the installer is required to (a) report
  // installed=false, (b) NOT leave a fresh OrionOmega pre-commit
  // hook on disk where one wasn't before, and (c) NOT leave any
  // .installing.* temp files behind.
  it('is fully transactional: a mid-install failure leaves NO partial hooks behind', () => {
    const fs = require('node:fs');
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    // Pre-existing pre-push that cannot be overwritten by a rename:
    // make it a directory. POSIX rename() refuses to clobber a
    // directory with a file, so the second rename throws and the
    // rollback path runs.
    mkdirSync(join(repoDir, '.git', 'hooks', 'pre-push'), { recursive: true });
    // Drop a sentinel inside so we can prove we didn't blow it away.
    writeFileSync(join(repoDir, '.git', 'hooks', 'pre-push', 'sentinel'), 'untouched', 'utf-8');

    const result = installSafeCommitHooks(repoDir);

    // (a) The install must report failure.
    expect(result.installed).toBe(false);
    // (b) No fresh OrionOmega pre-commit on disk — there was none
    // before and rollback put nothing there.
    const preCommitFinal = join(repoDir, '.git', 'hooks', 'pre-commit');
    expect(existsSync(preCommitFinal)).toBe(false);
    // The sabotaged pre-push directory must still be intact (we
    // never managed to rename over it, so it should be untouched).
    expect(fs.statSync(join(repoDir, '.git', 'hooks', 'pre-push')).isDirectory()).toBe(true);
    expect(readFileSync(join(repoDir, '.git', 'hooks', 'pre-push', 'sentinel'), 'utf-8')).toBe('untouched');
    // (c) No leftover temp files. Scan the hooks dir for anything
    // matching our `.installing.*` suffix.
    const leftovers = fs
      .readdirSync(join(repoDir, '.git', 'hooks'))
      .filter((n: string) => n.includes('.installing.'));
    expect(leftovers).toEqual([]);
  });

  it('rolls back to the prior pre-commit content when pre-push install fails mid-way', () => {
    const fs = require('node:fs');
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    // Pre-existing custom pre-commit hook the user already had.
    const prior = '#!/bin/sh\n# user custom hook\nexit 0\n';
    writeFileSync(join(repoDir, '.git', 'hooks', 'pre-commit'), prior, 'utf-8');
    // Sabotage pre-push so the second rename fails after pre-commit
    // has already been swapped into place — exactly the case the
    // rollback path is for.
    mkdirSync(join(repoDir, '.git', 'hooks', 'pre-push'), { recursive: true });

    const result = installSafeCommitHooks(repoDir);
    expect(result.installed).toBe(false);
    // The user's prior pre-commit content must be restored byte-for-byte.
    expect(readFileSync(join(repoDir, '.git', 'hooks', 'pre-commit'), 'utf-8')).toBe(prior);
    const leftovers = fs
      .readdirSync(join(repoDir, '.git', 'hooks'))
      .filter((n: string) => n.includes('.installing.'));
    expect(leftovers).toEqual([]);
  });

  // Runtime integration: spin up a real git repo, drop offending files
  // into the index / commits, then invoke the installed hooks directly
  // and assert exit code + stderr message. This is what the architect
  // specifically asked for — body string assertions don't prove the
  // hook behaves the way we claim under git.
  describe('runtime behaviour against a real git repo', () => {
    const { execFileSync, spawnSync } = require('node:child_process');

    function initRepo(): string {
      execFileSync('git', ['init', '-q', '-b', 'main', repoDir], { stdio: 'pipe' });
      execFileSync('git', ['-C', repoDir, 'config', 'user.email', 'test@example.com']);
      execFileSync('git', ['-C', repoDir, 'config', 'user.name', 'Test']);
      execFileSync('git', ['-C', repoDir, 'config', 'commit.gpgsign', 'false']);
      return repoDir;
    }

    function commitAll(msg: string): void {
      // -f forces inclusion despite global excludesFile (Replit's
      // /etc/.gitignore lists .env / node_modules). --no-verify
      // bypasses our own pre-commit hook in setup so we can
      // intentionally seed bad commits and then test pre-push against
      // them.
      execFileSync('git', ['-C', repoDir, 'add', '-A', '-f'], { stdio: 'pipe' });
      execFileSync('git', ['-C', repoDir, 'commit', '-q', '--no-verify', '--allow-empty', '-m', msg], { stdio: 'pipe' });
    }

    function runPrePushHook(): { status: number | null; stderr: string; stdout: string } {
      const { prePushHookPath } = installSafeCommitHooks(repoDir);
      // No stdin → falls back to walking HEAD tree (the audit mode).
      const result = spawnSync(prePushHookPath, [], { cwd: repoDir, encoding: 'utf-8' });
      return { status: result.status, stderr: result.stderr ?? '', stdout: result.stdout ?? '' };
    }

    function runPrePushHookWithRefs(stdin: string): { status: number | null; stderr: string; stdout: string } {
      const { prePushHookPath } = installSafeCommitHooks(repoDir);
      const result = spawnSync(prePushHookPath, [], { cwd: repoDir, encoding: 'utf-8', input: stdin });
      return { status: result.status, stderr: result.stderr ?? '', stdout: result.stdout ?? '' };
    }

    function runPreCommitHookAfterStaging(): { status: number | null; stderr: string; stdout: string } {
      const { preCommitHookPath } = installSafeCommitHooks(repoDir);
      // -f forces past global excludesFile so we can stage things git
      // would otherwise ignore.
      execFileSync('git', ['-C', repoDir, 'add', '-A', '-f'], { stdio: 'pipe' });
      const result = spawnSync(preCommitHookPath, [], { cwd: repoDir, encoding: 'utf-8' });
      return { status: result.status, stderr: result.stderr ?? '', stdout: result.stdout ?? '' };
    }

    it('pre-push passes (exit 0) on a clean repo with only safe files (HEAD fallback)', () => {
      initRepo();
      writeFileSync(join(repoDir, 'README.md'), '# hi\n', 'utf-8');
      writeFileSync(join(repoDir, 'src.ts'), 'export const x = 1;\n', 'utf-8');
      commitAll('safe commit');
      const r = runPrePushHook();
      expect(r.status).toBe(0);
      expect(r.stderr).toBe('');
    });

    it('pre-push refuses (exit 1) when a .env file is committed (HEAD fallback)', () => {
      initRepo();
      writeFileSync(join(repoDir, '.env'), 'SECRET=topsecret\n', 'utf-8');
      commitAll('leak attempt');
      const r = runPrePushHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/refusing to push/);
      expect(r.stderr).toMatch(/\.env \(secret \/ env file\)/);
    });

    it('pre-push refuses node_modules but allows .env.example through (HEAD fallback)', () => {
      initRepo();
      mkdirSync(join(repoDir, 'node_modules', 'foo'), { recursive: true });
      writeFileSync(join(repoDir, 'node_modules', 'foo', 'index.js'), 'x', 'utf-8');
      writeFileSync(join(repoDir, '.env.example'), 'KEY=changeme\n', 'utf-8');
      commitAll('mixed');
      const r = runPrePushHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/build artefact/);
      expect(r.stderr).not.toMatch(/\.env\.example/);
    });

    it('pre-push refuses (exit 1) on filenames with embedded newlines (hostile-filename hardening)', () => {
      initRepo();
      const hostile = `evil\nfile.txt`;
      writeFileSync(join(repoDir, hostile), 'x', 'utf-8');
      commitAll('hostile filename');
      const r = runPrePushHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/control characters/);
    });

    it('pre-push refuses (exit 1) on a .pem key file (HEAD fallback)', () => {
      initRepo();
      writeFileSync(join(repoDir, 'cert.pem'), '-----BEGIN PRIVATE KEY-----\n', 'utf-8');
      commitAll('key');
      const r = runPrePushHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/secret \/ key material/);
    });

    // Round-4 review: pre-push must walk EVERY commit being pushed,
    // not just HEAD. Regression for the case "bad blob committed in
    // commit B, then removed in commit C" — the HEAD tree is clean
    // but the bad blob is still in the pushed history and would be
    // refused by GitHub.
    it('pre-push walks every commit in the pushed range (catches blobs removed before HEAD)', () => {
      initRepo();
      // Commit 1: clean baseline.
      writeFileSync(join(repoDir, 'README.md'), '# hi\n', 'utf-8');
      commitAll('baseline');
      const baseline = execFileSync('git', ['-C', repoDir, 'rev-parse', 'HEAD'], { encoding: 'utf-8' }).trim();
      // Commit 2: introduces a .env (the offender).
      writeFileSync(join(repoDir, '.env'), 'SECRET=leak\n', 'utf-8');
      commitAll('leak in middle commit');
      // Commit 3: removes the offender, leaving HEAD clean.
      execFileSync('git', ['-C', repoDir, 'rm', '-f', '.env'], { stdio: 'pipe' });
      execFileSync('git', ['-C', repoDir, 'commit', '-q', '--no-verify', '-m', 'cleanup'], { stdio: 'pipe' });
      const head = execFileSync('git', ['-C', repoDir, 'rev-parse', 'HEAD'], { encoding: 'utf-8' }).trim();

      // HEAD tree alone is clean — the audit-mode fallback would NOT
      // catch this, which is exactly the gap.
      const audit = runPrePushHook();
      expect(audit.status).toBe(0);

      // But with stdin refs (simulating `git push origin main` against
      // a remote that's at `baseline`), the hook walks baseline..head
      // and MUST surface the offender.
      const stdin = `refs/heads/main ${head} refs/heads/main ${baseline}\n`;
      const r = runPrePushHookWithRefs(stdin);
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/\.env \(secret \/ env file\)/);
    });

    it('pre-push handles a brand-new branch (remote_sha = 0{40}) by walking all reachable history', () => {
      initRepo();
      writeFileSync(join(repoDir, '.env'), 'SECRET=x\n', 'utf-8');
      commitAll('new branch with secret');
      const head = execFileSync('git', ['-C', repoDir, 'rev-parse', 'HEAD'], { encoding: 'utf-8' }).trim();
      const stdin = `refs/heads/feature ${head} refs/heads/feature ${'0'.repeat(40)}\n`;
      const r = runPrePushHookWithRefs(stdin);
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/\.env \(secret \/ env file\)/);
    });

    it('pre-commit refuses (exit 1) when an unsafe file is staged', () => {
      initRepo();
      writeFileSync(join(repoDir, '.env'), 'SECRET=x\n', 'utf-8');
      const r = runPreCommitHookAfterStaging();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/refusing this commit/);
      expect(r.stderr).toMatch(/\.env \(secret \/ env file\)/);
    });

    it('pre-commit passes (exit 0) on a clean staged index', () => {
      initRepo();
      writeFileSync(join(repoDir, 'README.md'), '# hi\n', 'utf-8');
      writeFileSync(join(repoDir, 'src.ts'), 'export const x = 1;\n', 'utf-8');
      const r = runPreCommitHookAfterStaging();
      expect(r.status).toBe(0);
      expect(r.stderr).toBe('');
    });

    it('pre-commit catches build artefacts at staging time', () => {
      initRepo();
      mkdirSync(join(repoDir, 'node_modules', 'foo'), { recursive: true });
      writeFileSync(join(repoDir, 'node_modules', 'foo', 'index.js'), 'x', 'utf-8');
      const r = runPreCommitHookAfterStaging();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/build artefact/);
    });

    it('pre-commit catches a .pem key file in the staged index', () => {
      initRepo();
      writeFileSync(join(repoDir, 'cert.pem'), '-----BEGIN PRIVATE KEY-----\n', 'utf-8');
      const r = runPreCommitHookAfterStaging();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/secret \/ key material/);
    });
  });
});

describe('MAX_COMMITTABLE_BYTES', () => {
  it('stays comfortably under GitHub\'s 100 MB hard limit', () => {
    expect(MAX_COMMITTABLE_BYTES).toBe(95 * 1024 * 1024);
    expect(MAX_COMMITTABLE_BYTES).toBeLessThan(100 * 1024 * 1024);
  });
});
