/**
 * @module orchestration/coding/__tests__/safe-commit
 *
 * Tests for the coding-mode commit safety helpers (Task #209).
 *
 * Cover the four "done looks like" cases from the task spec:
 *   (a) fresh repo with no `.gitignore` + an oversize binary → push refused
 *   (b) repo with partial `.gitignore` → only missing entries appended
 *   (c) `.env` always excluded even when `.gitignore` doesn't list it
 *   (d) clean repo with no offending files → behaviour unchanged
 *
 * The helpers are pure I/O against `repoDir`, so each test sets up a
 * tiny throwaway directory under the OS temp dir and tears it down on
 * exit. We deliberately do NOT shell out to `git`: the helpers are
 * `git`-free by design, and that's what makes them testable here
 * without forking processes.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import {
  mkdtempSync,
  rmSync,
  writeFileSync,
  readFileSync,
  mkdirSync,
  existsSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  DEFAULT_GITIGNORE_ENTRIES,
  MAX_COMMITTABLE_BYTES,
  ensureSafeGitignore,
  findUnsafeFiles,
  prepareSafeCommit,
  installSafeCommitHook,
  CommitSafetyError,
  formatCommitSafetyMessage,
} from '../safe-commit.js';

let repoDir: string;

beforeEach(() => {
  repoDir = mkdtempSync(join(tmpdir(), 'safe-commit-test-'));
});

afterEach(() => {
  try { rmSync(repoDir, { recursive: true, force: true }); } catch { /* best effort */ }
});

describe('ensureSafeGitignore', () => {
  it('creates a fresh .gitignore with the full default set when none exists', () => {
    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(true);
    expect(result.added).toEqual([...DEFAULT_GITIGNORE_ENTRIES]);
    const content = readFileSync(result.gitignorePath, 'utf-8');
    expect(content).toMatch(/Auto-generated by OrionOmega coding mode/);
    for (const entry of DEFAULT_GITIGNORE_ENTRIES) {
      expect(content).toContain(entry);
    }
  });

  it('appends only the missing entries to a partial .gitignore (case b)', () => {
    // Pretend the user already curated a few entries by hand.
    const userCurated = '# my own ignores\nnode_modules/\ndist/\n*.log\n';
    writeFileSync(join(repoDir, '.gitignore'), userCurated, 'utf-8');

    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(false);

    // The three entries above are part of the default set, so they must
    // NOT appear in `added` — that's the user-curated content we promised
    // to preserve.
    expect(result.added).not.toContain('node_modules/');
    expect(result.added).not.toContain('dist/');
    expect(result.added).not.toContain('*.log');
    // Entries the user didn't list must show up.
    expect(result.added).toContain('.env');
    expect(result.added).toContain('.next/');
    expect(result.added).toContain('coverage/');

    const after = readFileSync(result.gitignorePath, 'utf-8');
    // Original content must be preserved verbatim at the top.
    expect(after.startsWith(userCurated)).toBe(true);
    // Appended block carries the audit-trail comment.
    expect(after).toMatch(/safe-commit defaults/);
  });

  it('is a no-op when the .gitignore already covers every default entry (case d)', () => {
    const full = DEFAULT_GITIGNORE_ENTRIES.join('\n') + '\n';
    writeFileSync(join(repoDir, '.gitignore'), full, 'utf-8');
    const result = ensureSafeGitignore(repoDir);
    expect(result.created).toBe(false);
    expect(result.added).toEqual([]);
    // File contents are byte-for-byte unchanged: no spurious append, no
    // trailing-newline rewriting that would noisy-up the user's diff.
    expect(readFileSync(result.gitignorePath, 'utf-8')).toBe(full);
  });

  it('treats whitespace-padded entries as already-present (no duplicate appends)', () => {
    writeFileSync(join(repoDir, '.gitignore'), '  node_modules/  \n', 'utf-8');
    const result = ensureSafeGitignore(repoDir);
    expect(result.added).not.toContain('node_modules/');
  });
});

describe('findUnsafeFiles', () => {
  it('flags files larger than the 95 MB GitHub-safe ceiling (case a)', () => {
    // We use a small `maxBytes` instead of writing 95 MB to disk —
    // behaviour is identical, runtime is a millisecond.
    writeFileSync(join(repoDir, 'big.bin'), 'x'.repeat(2048), 'utf-8');
    writeFileSync(join(repoDir, 'small.txt'), 'hello', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir, { maxBytes: 1024 });
    const oversize = unsafe.filter((u) => u.reason === 'oversize');
    expect(oversize).toHaveLength(1);
    expect(oversize[0]?.path).toBe('big.bin');
    expect(oversize[0]?.bytes).toBe(2048);
  });

  it('flags .env, .env.local, and *.env.production as secrets (case c)', () => {
    writeFileSync(join(repoDir, '.env'), 'SECRET=1', 'utf-8');
    writeFileSync(join(repoDir, '.env.local'), 'SECRET=2', 'utf-8');
    writeFileSync(join(repoDir, '.env.production'), 'SECRET=3', 'utf-8');
    // .env.example must NOT be flagged — it's the conventional template.
    writeFileSync(join(repoDir, '.env.example'), 'SECRET=', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    const paths = unsafe.filter((u) => u.reason === 'secret').map((u) => u.path).sort();
    expect(paths).toEqual(['.env', '.env.local', '.env.production']);
  });

  it('flags *.pem / *.key / *.p12 as secrets', () => {
    writeFileSync(join(repoDir, 'cert.pem'), 'pem', 'utf-8');
    writeFileSync(join(repoDir, 'private.key'), 'key', 'utf-8');
    writeFileSync(join(repoDir, 'truststore.p12'), 'p12', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe.map((u) => u.path).sort()).toEqual(['cert.pem', 'private.key', 'truststore.p12']);
    expect(unsafe.every((u) => u.reason === 'secret')).toBe(true);
  });

  it('flags top-level node_modules / dist / .next as build artefacts', () => {
    mkdirSync(join(repoDir, 'node_modules', '@scope', 'pkg'), { recursive: true });
    writeFileSync(join(repoDir, 'node_modules', '@scope', 'pkg', 'index.js'), 'x', 'utf-8');
    mkdirSync(join(repoDir, 'dist'), { recursive: true });
    writeFileSync(join(repoDir, 'dist', 'bundle.js'), 'x', 'utf-8');
    mkdirSync(join(repoDir, '.next'), { recursive: true });
    writeFileSync(join(repoDir, '.next', 'app.js'), 'x', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    const buildPaths = unsafe.filter((u) => u.reason === 'build-artefact').map((u) => u.path).sort();
    expect(buildPaths).toEqual([
      '.next/app.js',
      'dist/bundle.js',
      'node_modules/@scope/pkg/index.js',
    ]);
  });

  it('does NOT flag legitimately-named files that merely contain artefact substrings', () => {
    // `node_modules.md` under `docs/` is a perfectly valid documentation
    // file. The deny-list is anchored to the *first* path segment so this
    // doesn't get caught.
    mkdirSync(join(repoDir, 'docs'), { recursive: true });
    writeFileSync(join(repoDir, 'docs', 'node_modules.md'), '# notes', 'utf-8');
    writeFileSync(join(repoDir, 'README.md'), '# readme', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe).toEqual([]);
  });

  it('skips the .git directory entirely (never reports git internals)', () => {
    mkdirSync(join(repoDir, '.git', 'objects'), { recursive: true });
    // A pretend pack file over 95 MB — this would be a false positive if
    // we walked .git, since git's own object DB legitimately exceeds the
    // commit limit on large repos.
    writeFileSync(join(repoDir, '.git', 'objects', 'pack-xxx'), 'x'.repeat(2048), 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir, { maxBytes: 1024 });
    expect(unsafe).toEqual([]);
  });

  it('returns no unsafe files for a clean source-only repo (case d)', () => {
    writeFileSync(join(repoDir, 'README.md'), '# project', 'utf-8');
    writeFileSync(join(repoDir, 'package.json'), '{}', 'utf-8');
    mkdirSync(join(repoDir, 'src'), { recursive: true });
    writeFileSync(join(repoDir, 'src', 'index.ts'), 'export {};', 'utf-8');
    const { unsafe } = findUnsafeFiles(repoDir);
    expect(unsafe).toEqual([]);
  });
});

describe('prepareSafeCommit', () => {
  it('reproduces the user\'s Legal-repo failure: ensures gitignore + throws on oversize node_modules (case a)', () => {
    // Fresh repo, no .gitignore — exactly the state the Legal repo was in.
    mkdirSync(join(repoDir, 'node_modules', '@next', 'swc-linux-x64-gnu'), { recursive: true });
    // Use a small `maxBytes` to simulate the 125 MB next-swc binary
    // without writing 125 MB of disk in the test.
    const huge = join(repoDir, 'node_modules', '@next', 'swc-linux-x64-gnu', 'next-swc.linux-x64-gnu.node');
    writeFileSync(huge, 'x'.repeat(2048), 'utf-8');
    writeFileSync(join(repoDir, 'package.json'), '{}', 'utf-8');

    // The bare prepareSafeCommit (default 95 MB) wouldn't trip on a 2 KB
    // file, but our findUnsafeFiles also flags it as a build artefact, so
    // the throw still fires for the right reason.
    expect(() => prepareSafeCommit(repoDir)).toThrowError(CommitSafetyError);
    // And the .gitignore was created on the way out (so the next run
    // wouldn't even produce the same files in the staging set).
    expect(existsSync(join(repoDir, '.gitignore'))).toBe(true);
  });

  it('returns a clean result with the gitignore audit trail when nothing is unsafe (case d)', () => {
    writeFileSync(join(repoDir, 'README.md'), '# project', 'utf-8');
    const result = prepareSafeCommit(repoDir);
    expect(result.refused).toEqual([]);
    expect(result.gitignore.created).toBe(true);
    expect(result.gitignore.added.length).toBeGreaterThan(0);
  });
});

describe('formatCommitSafetyMessage', () => {
  it('lists each offending file with a human-readable size and reason', () => {
    const msg = formatCommitSafetyMessage([
      { path: 'node_modules/big.bin', reason: 'oversize', bytes: 125 * 1024 * 1024 },
      { path: '.env', reason: 'secret', bytes: 42 },
    ]);
    expect(msg).toMatch(/Refusing to commit 2 files/);
    expect(msg).toContain('node_modules/big.bin');
    expect(msg).toContain('125.00 MB');
    expect(msg).toContain('.env');
    expect(msg).toContain('secret');
    expect(msg).toMatch(/Git LFS/);
  });
});

describe('installSafeCommitHook', () => {
  it('writes an executable pre-push hook into .git/hooks/', () => {
    mkdirSync(join(repoDir, '.git'), { recursive: true });
    const result = installSafeCommitHook(repoDir);
    expect(result.installed).toBe(true);
    expect(result.hookPath).toBe(join(repoDir, '.git', 'hooks', 'pre-push'));
    expect(existsSync(result.hookPath)).toBe(true);
    const stat = require('node:fs').statSync(result.hookPath);
    // 0o111 = owner/group/other execute bits — at least owner+ must be set.
    expect(stat.mode & 0o100).toBeTruthy();
  });

  it('embeds the 95 MB ceiling, build-artefact deny-list, and secret patterns in the hook', () => {
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    const { hookPath } = installSafeCommitHook(repoDir);
    const body = readFileSync(hookPath, 'utf-8');
    expect(body).toMatch(/^#!\/usr\/bin\/env perl/);
    expect(body).toContain('95 * 1024 * 1024');
    // True NUL-record processing via `local $/ = "\0"`. No shell-level
    // round-trip means filenames with embedded newlines/tabs survive
    // intact through the classifier.
    expect(body).toContain('local $/ = "\\0"');
    expect(body).toContain("'git', 'ls-tree', '-r', '-l', '-z', 'HEAD'");
    // Control-char rejection range MUST cover TAB (0x09), LF (0x0A),
    // and CR (0x0D). The 0x01-0x1F range does so by construction.
    expect(body).toMatch(/\[\\x01-\\x1f\]/);
    // Build artefacts — anchored first-segment match in the perl regex.
    expect(body).toMatch(/node_modules\|/);
    expect(body).toMatch(/\.next\|/);
    expect(body).toMatch(/dist\|build/);
    expect(body).toMatch(/coverage/);
    // Secrets / key material — basename suffix match.
    expect(body).toMatch(/pem\|key\|p12\|pfx/);
    // Conventional placeholders must be allowed through.
    expect(body).toContain('.env.example');
    expect(body).toContain('.env.sample');
    // The hook must signal failure with a clear, user-readable banner so
    // the executor's "push failure → run failure" wiring carries it
    // verbatim to the user.
    expect(body).toMatch(/refusing to push/);
    expect(body).toMatch(/exit 1/);
    // Hostile-filename hardening: parse must use NUL-delimited ls-tree
    // output so paths with embedded newlines/tabs can't smuggle past.
    expect(body).toMatch(/control characters/);
  });

  it('overwrites a stale hook on every install (idempotent re-installation)', () => {
    mkdirSync(join(repoDir, '.git', 'hooks'), { recursive: true });
    const stale = join(repoDir, '.git', 'hooks', 'pre-push');
    writeFileSync(stale, '#!/bin/sh\necho stale\n', 'utf-8');
    const { installed } = installSafeCommitHook(repoDir);
    expect(installed).toBe(true);
    expect(readFileSync(stale, 'utf-8')).toMatch(/OrionOmega safe-commit hook/);
  });

  it('is a no-op (installed=false) when .git is missing — no fabricated git dir', () => {
    // No .git directory at all (e.g. a sandbox that wasn't cloned).
    const result = installSafeCommitHook(repoDir);
    expect(result.installed).toBe(false);
    expect(existsSync(join(repoDir, '.git'))).toBe(false);
  });

  // Runtime integration: spin up a real git repo, drop offending files
  // into HEAD, then invoke the installed hook directly via /bin/sh and
  // assert the actual exit code + stderr message. This is the test the
  // architect specifically asked for — string assertions on the hook
  // body don't prove the awk script behaves the way we claim.
  describe('runtime behaviour against a real git repo', () => {
    const { execFileSync, spawnSync } = require('node:child_process');

    function initRepo(): string {
      execFileSync('git', ['init', '-q', '-b', 'main', repoDir], { stdio: 'pipe' });
      execFileSync('git', ['-C', repoDir, 'config', 'user.email', 'test@example.com']);
      execFileSync('git', ['-C', repoDir, 'config', 'user.name', 'Test']);
      execFileSync('git', ['-C', repoDir, 'config', 'commit.gpgsign', 'false']);
      return repoDir;
    }

    function commitAll(msg: string): void {
      // -f forces inclusion of paths matched by global excludesFile
      // (e.g. /etc/.gitignore on Replit which lists .env / node_modules).
      // We're testing the hook, not git's own ignore semantics, so we
      // explicitly stage every file in the working tree regardless of
      // any inherited ignore rules.
      execFileSync('git', ['-C', repoDir, 'add', '-A', '-f'], { stdio: 'pipe' });
      execFileSync('git', ['-C', repoDir, 'commit', '-q', '--allow-empty', '-m', msg], { stdio: 'pipe' });
    }

    function runHook(): { status: number | null; stderr: string; stdout: string } {
      const { hookPath } = installSafeCommitHook(repoDir);
      // Invoke the hook directly — git itself execs the file, honouring
      // its shebang (`#!/usr/bin/env perl`). Calling /bin/sh on it would
      // mis-interpret the perl source as shell.
      const result = spawnSync(hookPath, [], { cwd: repoDir, encoding: 'utf-8' });
      return { status: result.status, stderr: result.stderr ?? '', stdout: result.stdout ?? '' };
    }

    it('passes (exit 0) on a clean repo with only safe files', () => {
      initRepo();
      writeFileSync(join(repoDir, 'README.md'), '# hi\n', 'utf-8');
      writeFileSync(join(repoDir, 'src.ts'), 'export const x = 1;\n', 'utf-8');
      commitAll('safe commit');
      const r = runHook();
      expect(r.status).toBe(0);
      expect(r.stderr).toBe('');
    });

    it('refuses (exit 1) when a .env file is committed', () => {
      initRepo();
      writeFileSync(join(repoDir, '.env'), 'SECRET=topsecret\n', 'utf-8');
      commitAll('leak attempt');
      const r = runHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/refusing to push/);
      expect(r.stderr).toMatch(/\.env \(secret \/ env file\)/);
    });

    it('refuses when a node_modules path is committed but allows .env.example through', () => {
      initRepo();
      mkdirSync(join(repoDir, 'node_modules', 'foo'), { recursive: true });
      writeFileSync(join(repoDir, 'node_modules', 'foo', 'index.js'), 'x', 'utf-8');
      writeFileSync(join(repoDir, '.env.example'), 'KEY=changeme\n', 'utf-8');
      commitAll('mixed');
      const r = runHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/build artefact/);
      // .env.example must NOT appear in the offender list.
      expect(r.stderr).not.toMatch(/\.env\.example/);
    });

    it('refuses (exit 1) on filenames containing embedded newlines — the hostile-filename hardening claim', () => {
      initRepo();
      // POSIX filesystems allow \n in filenames. Create one with a
      // literal LF in the middle of the path to prove the NUL-record
      // awk parse keeps the filename intact end-to-end.
      // Single-segment filename with an embedded LF — no slash, so
      // the FS write doesn't try to create a phantom directory.
      const hostile = `evil\nfile.txt`;
      writeFileSync(join(repoDir, hostile), 'x', 'utf-8');
      commitAll('hostile filename');
      const r = runHook();
      expect(r.status).toBe(1);
      // The exact rejection reason is "control characters" — the LF
      // (0x0A) is in the 0x01–0x1F range.
      expect(r.stderr).toMatch(/control characters/);
    });

    it('refuses (exit 1) on a .pem key file', () => {
      initRepo();
      writeFileSync(join(repoDir, 'cert.pem'), '-----BEGIN PRIVATE KEY-----\n', 'utf-8');
      commitAll('key');
      const r = runHook();
      expect(r.status).toBe(1);
      expect(r.stderr).toMatch(/secret \/ key material/);
    });
  });
});

describe('MAX_COMMITTABLE_BYTES', () => {
  it('stays comfortably under GitHub\'s 100 MB hard limit', () => {
    expect(MAX_COMMITTABLE_BYTES).toBe(95 * 1024 * 1024);
    expect(MAX_COMMITTABLE_BYTES).toBeLessThan(100 * 1024 * 1024);
  });
});
